---
- name: Instalación de dependencias
  apt: 
    name: ['python-apt']
    state: latest
    update_cache: yes

- name: Instalación de paquetes
  apt: 
    name: ['tmux', 'gawk', 'perl', 'sed']

- name: Inserta líneas al final del archivo
  blockinfile:
    path: "{{ home }}/.tmux.conf"
    block: | 
      # ip address en la status bar
      set -g status-left-length 70
      set -g status-left "#[fg=brightblue]#(ip addr show dev enp0s8 | grep "inet[^6]" | awk '{print $2}') #[fg=red]#(ip addr show dev tun0 | grep "inet[^6]" | awk '{print $2}')" 
      
      # cierra ventanas y paneles sin confirmaciones
      bind-key & kill-window
      bind-key x kill-pane
      
      # Inicia sesiones con el numero 1
      set-option -g base-index 1
      setw -g pane-base-index 1
      
      # Mejora las divisiones
      bind | split-window -h -c "#{pane_current_path}"
      bind - split-window -v -c "#{pane_current_path}"
      bind c new-window -c "#{pane_current_path}"
      
      # Mejora los colores
      set -g default-terminal "screen-256color"
      
      # Recarga del archivo de configuración
      unbind r
      bind r source-file ~/.tmux.conf
      
      # Para dejar de renombrar paneles automaticamente
      set-option -g allow-rename off
      
      # Mejora el delay cuando le damos al escape
      set -sg escape-time 0

      # Status Bar
      setw -g monitor-activity on
      set -g visual-activity on
    create: yes	
    owner: "{{ user }}"
    group: "{{ group }}"


