---
- include_vars: ../../vars_main.yml

- name: Descargar e instalar lsd
  apt:
    deb: "{{ lsd_repo }}/{{ lsd_version }}/lsd_{{ lsd_version }}_amd64.deb"

- name: Crea el directorio para los archivos de configuraci√≥n
  file:
    path: "/home/{{ usuario }}/.config/lsd"
    state: directory
    mode: 0775
    owner: "{{ usuario }}"
    group: "{{ usuario }}"

- name: Copia archivo con configuracion
  copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/lsd/"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0775
  with_items:
    - config.yaml

- name: Descargando y copiando NerdFonts
  unarchive:
    src: "{{ lsd_nerdfonts }}"
    dest: /usr/share/fonts/
    remote_src: true

- name: Agregando alias en bashrc
  lineinfile:
    dest: "{{ home }}/.bashrc"
    line: "alias ls='lsd'"
    owner: "{{ usuario }}"
